### ISSUE TITLE
Anchor in labels are unclickable

### ISSUE THREAD

**Issue by royduin** [arthurgouveia/prettyCheckable#64]
When I use anchor tags in a label it performs as a checkbox which results in a unclickable anchor when I remove the styling

``` css
label a {
    height: auto;
    width: auto;
    display: inline;
    float: none;
    background: transparent;
}
```
